import { Link } from 'react-router-dom'
import { motion } from 'framer-motion'
import {
  Heart, FlaskConical, LayoutGrid, ShieldAlert,
  ArrowRight, Phone, ExternalLink, CheckCircle2,
  Globe,
} from 'lucide-react'

/* ── Custom SVGs ───────────────────────────────────────────────────────── */
const GithubIcon = (props) => (
  <svg
    {...props}
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth="2"
    strokeLinecap="round"
    strokeLinejoin="round"
  >
    <path d="M15 22v-4a4.8 4.8 0 0 0-1-3.5c3 0 6-2 6-5.5.08-1.25-.27-2.48-1-3.5.28-1.15.28-2.35 0-3.5 0 0-1 0-3 1.5-2.64-.5-5.36-.5-8 0C6 2 5 2 5 2c-.3 1.15-.3 2.35 0 3.5A5.403 5.403 0 0 0 4 9c0 3.5 3 5.5 6 5.5-.39.49-.68 1.05-.85 1.65-.17.6-.22 1.23-.15 1.85v4" />
    <path d="M9 18c-4.51 2-5-2-7-2" />
  </svg>
)

const LinkedinIcon = (props) => (
  <svg
    {...props}
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth="2"
    strokeLinecap="round"
    strokeLinejoin="round"
  >
    <path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z" />
    <rect width="4" height="12" x="2" y="9" />
    <circle cx="4" cy="4" r="2" />
  </svg>
)
import Badge from '../components/ui/Badge'
import Button from '../components/ui/Button'

/* ── Animation helper ───────────────────────────────────────────────────── */
const fadeUp = (delay = 0) => ({
  initial: { opacity: 0, y: 22 },
  whileInView: { opacity: 1, y: 0 },
  viewport: { once: true, margin: '-60px' },
  transition: { duration: 0.5, delay, ease: [0.4, 0, 0.2, 1] },
})

/* ── Section wrapper ────────────────────────────────────────────────────── */
function Section({ id, icon: Icon, badge, title, iconColor = 'text-primary dark:text-primaryDark', children }) {
  return (
    <section id={id} className="py-16 sm:py-20">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        <motion.div {...fadeUp(0)} className="flex items-center gap-3 mb-5">
          <span className={`p-2.5 rounded-xl bg-primary/8 dark:bg-primaryDark/10 ${iconColor}`}>
            <Icon size={18} strokeWidth={2.2} />
          </span>
          <Badge text={badge} color="indigo" />
        </motion.div>
        <motion.h2 {...fadeUp(0.06)} className="text-3xl sm:text-4xl font-extrabold text-gray-900 dark:text-white mb-6 tracking-tight">
          {title}
        </motion.h2>
        {children}
      </div>
    </section>
  )
}

/* ── Assessment category cards ──────────────────────────────────────────── */
const CATEGORIES = [
  {
    name: 'Personality',
    color: 'bg-indigo-50 dark:bg-indigo-950/30 border-indigo-200 dark:border-indigo-700/40',
    badge: 'indigo',
    desc: 'Explore stable patterns in how you think, feel and behave. Includes the research-validated Big Five model covering Openness, Conscientiousness, Extraversion, Agreeableness, and Neuroticism.',
    examples: ['Big Five (BFI-44)'],
  },
  {
    name: 'Mental Health',
    color: 'bg-emerald-50 dark:bg-emerald-950/30 border-emerald-200 dark:border-emerald-700/40',
    badge: 'green',
    desc: 'Validated screening tools for common mental health concerns used globally in clinical and research settings. Results are for awareness only and do not replace professional evaluation.',
    examples: ['PHQ-9 Depression Screening', 'GAD-7 Anxiety Screening', 'Rosenberg Self-Esteem Scale'],
  },
  {
    name: 'Behavioral',
    color: 'bg-violet-50 dark:bg-violet-950/30 border-violet-200 dark:border-violet-700/40',
    badge: 'purple',
    desc: 'Understand your relational patterns and how you connect with others. The ECR-R reveals your attachment style across Anxiety and Avoidance dimensions.',
    examples: ['Attachment Style (ECR-R)'],
  },
]

/* ── Science steps ──────────────────────────────────────────────────────── */
const SCIENCE_STEPS = [
  { num: '01', title: 'Validated Scales',     text: 'Every assessment is based on a published, peer-reviewed psychometric instrument with documented reliability and validity evidence across diverse populations.' },
  { num: '02', title: 'Standardised Scoring', text: 'Responses are scored using the exact formulas defined by the original researchers, including reverse-scoring where required, and normalised to intuitive 0–100 percentages.' },
  { num: '03', title: 'Contextual Ranges',    text: 'Score ranges and interpretation labels are derived from population norms and clinical thresholds documented in the original validation studies.' },
  { num: '04', title: 'AI Narrative Layer',   text: 'Personalised written insights are generated by Groq\'s llama3 model, guided by a structured prompt designed to be empathetic, evidence-informed, and encouraging — never diagnostic.' },
]

/* ── Crisis resources ────────────────────────────────────────────────────── */
const CRISIS_LINES = [
  { name: 'iCall (India)',      contact: '9152987821',    href: 'tel:9152987821' },
  { name: 'Vandrevala Foundation', contact: '1860-2662-345', href: 'tel:18602662345' },
  { name: 'Crisis Text Line',   contact: 'Text HOME to 741741', href: 'https://crisistextline.org' },
  { name: 'Befrienders',        contact: 'befrienders.org',     href: 'https://befrienders.org' },
]

/* ════════════════════════════════════════════════════════════════════════════
   PAGE
══════════════════════════════════════════════════════════════════════════════ */
export default function About() {
  return (
    <div className="bg-surfaceLight dark:bg-surfaceDark">

      {/* ── Hero ──────────────────────────────────────────────────────── */}
      <div className="bg-gradient-to-br from-indigo-50 via-white to-violet-50 dark:from-surfaceDark dark:via-[#12122A] dark:to-[#0e0e20] border-b border-gray-200 dark:border-gray-800 overflow-hidden">
        <div className="max-w-6xl mx-auto px-6 sm:px-8 lg:px-12 py-16">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-10 items-center">
            <div>
              <motion.div {...fadeUp(0)}>
                <Badge text="About MindMetric" color="indigo" className="mb-5" />
              </motion.div>
              <motion.h1 {...fadeUp(0.07)} className="text-4xl sm:text-5xl font-extrabold text-gray-900 dark:text-white mb-5 tracking-tight leading-tight">
                Psychology for{' '}
                <span className="bg-gradient-to-r from-primary to-accent bg-clip-text text-transparent">Everyone</span>
              </motion.h1>
              <motion.p {...fadeUp(0.14)} className="text-base text-gray-500 dark:text-gray-400 max-w-xl leading-relaxed">
                MindMetric exists to make validated psychological science freely accessible — no jargon, no gatekeeping, no sign-up required.
              </motion.p>
            </div>
            <motion.div
              initial={{ opacity: 0, x: 30 }} whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true }} transition={{ duration: 0.7, delay: 0.1 }}
              className="hidden lg:block"
            >
              <div className="relative">
                <div className="absolute inset-0 rounded-3xl bg-gradient-to-br from-primary/20 to-accent/20 blur-2xl scale-110" />
                <img src="/images/about_indian_3.jpg" alt="Self-discovery and psychology" className="relative w-full rounded-3xl shadow-xl shadow-primary/15 object-cover object-center aspect-[4/3]" />
              </div>
            </motion.div>
          </div>
        </div>
      </div>

      {/* ════ MISSION ════════════════════════════════════════════════════ */}
      <div className="border-b border-gray-100 dark:border-gray-800/60">
        <Section id="mission" icon={Heart} badge="Our Mission" title="Making Psychology Accessible">
          <div className="space-y-4 text-base text-gray-600 dark:text-gray-300 leading-relaxed">
            <motion.p {...fadeUp(0.08)}>
              For decades, psychological self-knowledge has been locked behind expensive consultations, paywalled journals, and complex clinical terminology. MindMetric was built on a simple conviction: understanding your own mind should not require a prescription or a credit card.
            </motion.p>
            <motion.p {...fadeUp(0.13)}>
              We take scientifically validated psychometric instruments — the same tools used by researchers and clinicians worldwide — and present them in a clean, approachable format accessible to any curious person. Every assessment is free, private, and instant. Your data lives only on your device.
            </motion.p>
            <motion.p {...fadeUp(0.18)}>
              Self-knowledge is the foundation of wellbeing. When you understand your personality, your emotional patterns, and your relational style, you are better equipped to make intentional decisions, build healthier relationships, and seek the right kind of support when you need it.
            </motion.p>
          </div>
        </Section>
      </div>

      {/* ════ SCIENCE ════════════════════════════════════════════════════ */}
      <div className="bg-white dark:bg-[#0c0c1a] border-b border-gray-100 dark:border-gray-800/60">
        <Section id="science" icon={FlaskConical} badge="The Science" title="How the Assessments Work">
          <motion.p {...fadeUp(0.07)} className="text-base text-gray-600 dark:text-gray-300 leading-relaxed mb-10">
            Every assessment on MindMetric follows the same four-stage process from raw response to personalised insight:
          </motion.p>

          <div className="grid grid-cols-1 lg:grid-cols-2 gap-10 items-start">
            {/* Steps */}
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-5">
              {SCIENCE_STEPS.map(({ num, title, text }, i) => (
                <motion.div
                  key={num} {...fadeUp(0.08 + i * 0.07)}
                  className="relative p-6 rounded-2xl border border-gray-200 dark:border-gray-700 bg-cardLight dark:bg-cardDark"
                >
                  <span className="absolute top-4 right-5 text-4xl font-extrabold text-gray-100 dark:text-gray-800 leading-none select-none">{num}</span>
                  <h3 className="text-sm font-bold text-gray-900 dark:text-white mb-2">{title}</h3>
                  <p className="text-sm text-gray-500 dark:text-gray-400 leading-relaxed">{text}</p>
                </motion.div>
              ))}
            </div>

            {/* Science illustration */}
            <motion.div
              initial={{ opacity: 0, x: 24 }} whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true }} transition={{ duration: 0.6, delay: 0.1 }}
              className="flex items-center justify-center"
            >
              <div className="relative w-full max-w-sm">
                <div className="absolute inset-0 rounded-3xl bg-gradient-to-br from-teal-500/20 to-indigo-500/20 blur-2xl" />
                <img src="/images/taking_real.jpg" alt="Research-backed psychology" className="relative w-full h-full object-cover rounded-3xl shadow-xl" />
                <div className="absolute inset-0 rounded-3xl bg-gradient-to-t from-indigo-950/30 to-transparent" />
              </div>
            </motion.div>
          </div>
        </Section>
      </div>

      {/* ════ CATEGORIES ═════════════════════════════════════════════════ */}
      <div className="border-b border-gray-100 dark:border-gray-800/60">
        <Section id="assessments" icon={LayoutGrid} badge="The Assessments" title="What We Offer">
          <motion.p {...fadeUp(0.07)} className="text-base text-gray-600 dark:text-gray-300 leading-relaxed mb-8">
            Our library spans three core psychological domains. Each assessment was selected based on its scientific standing, citation record, and relevance to everyday self-understanding.
          </motion.p>
          <div className="space-y-5">
            {CATEGORIES.map(({ name, color, badge, desc, examples }, i) => (
              <motion.div key={name} {...fadeUp(0.08 + i * 0.08)} className={`p-6 rounded-2xl border ${color}`}>
                <div className="flex items-center gap-2.5 mb-3">
                  <Badge text={name} color={badge} />
                </div>
                <p className="text-sm text-gray-600 dark:text-gray-300 leading-relaxed mb-3">{desc}</p>
                <div className="flex flex-wrap gap-2">
                  {examples.map(ex => (
                    <span key={ex} className="flex items-center gap-1.5 text-xs text-gray-500 dark:text-gray-400">
                      <CheckCircle2 size={12} className="text-primary dark:text-primaryDark" />
                      {ex}
                    </span>
                  ))}
                </div>
              </motion.div>
            ))}
          </div>
          <motion.div {...fadeUp(0.3)} className="mt-8">
            <Link to="/assessments">
              <Button variant="primary" rightIcon={<ArrowRight size={15} />}>Explore the Full Library</Button>
            </Link>
          </motion.div>
        </Section>
      </div>

      {/* ════ DISCLAIMERS ════════════════════════════════════════════════ */}
      <div className="bg-white dark:bg-[#0c0c1a]">
        <Section id="disclaimer" icon={ShieldAlert} badge="Important Disclaimers" title="Please Read Carefully" iconColor="text-amber-500">
          {/* Main disclaimer box */}
          <motion.div {...fadeUp(0.08)} className="p-6 sm:p-8 rounded-2xl border-2 border-amber-300 dark:border-amber-700/60 bg-amber-50 dark:bg-amber-950/30 mb-6">
            <p className="text-xs font-bold uppercase tracking-widest text-amber-700 dark:text-amber-400 mb-5">
              Educational Use Only — Not a Clinical Tool
            </p>
            <div className="space-y-4 text-sm text-amber-800 dark:text-amber-300/90 leading-relaxed">
              <p>
                <strong>MindMetric is not a medical service.</strong> All assessments provided on this platform are strictly for educational and self-awareness purposes. They are not intended to diagnose, treat, cure, or prevent any mental health condition or medical disorder.
              </p>
              <p>
                The results generated by MindMetric — including scores, interpretation labels, range descriptions, and AI-generated narrative insights — do not constitute a clinical diagnosis and must not be used as a substitute for professional psychological, psychiatric, or medical evaluation and treatment.
              </p>
              <p>
                Psychometric instruments are probabilistic tools developed at a population level. Individual results can be influenced by your mood on the day, question misunderstanding, response bias, cultural factors, and many other variables. A single assessment cannot fully capture the complexity of a human being.
              </p>
              <p>
                The AI-generated insights are produced by a large language model and, while guided by a structured psychology-informed prompt, are not reviewed by licensed clinicians. They should be treated as a starting point for reflection, not as professional advice.
              </p>
              <p>
                <strong>If you are experiencing emotional distress, thoughts of self-harm, or symptoms that are impacting your daily life, please reach out to a licensed mental health professional immediately.</strong> Self-assessment tools are not a replacement for human care.
              </p>
            </div>
          </motion.div>

          {/* Crisis resources */}
          <motion.div {...fadeUp(0.15)}>
            <p className="text-sm font-semibold text-gray-700 dark:text-gray-200 mb-4 flex items-center gap-2">
              <Phone size={14} className="text-red-500" /> If you need immediate support
            </p>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              {CRISIS_LINES.map(({ name, contact, href }) => (
                <a
                  key={name} href={href}
                  target={href.startsWith('http') ? '_blank' : undefined}
                  rel="noopener noreferrer"
                  className="flex items-center justify-between gap-3 px-4 py-3 rounded-xl border border-red-200 dark:border-red-800/40 bg-red-50 dark:bg-red-950/25 hover:border-red-300 dark:hover:border-red-700 transition-colors duration-200"
                >
                  <div>
                    <p className="text-xs font-semibold text-red-700 dark:text-red-300">{name}</p>
                    <p className="text-[11px] text-red-500 dark:text-red-400 mt-0.5">{contact}</p>
                  </div>
                  <ExternalLink size={12} className="text-red-400 dark:text-red-500 flex-shrink-0" />
                </a>
              ))}
            </div>
          </motion.div>

          {/* Liability note */}
          <motion.p {...fadeUp(0.22)} className="mt-8 text-xs text-gray-400 dark:text-gray-500 leading-relaxed border-t border-gray-200 dark:border-gray-800 pt-6">
            By using MindMetric you acknowledge that you have read and understood this disclaimer. The creators and operators of MindMetric accept no liability for decisions made based on assessment results. All intellectual property rights in the assessment instruments belong to their respective authors and publishers.
          </motion.p>
        </Section>
      </div>

      {/* ════ DEVELOPER ══════════════════════════════════════════════════ */}
      <div className="border-t border-gray-100 dark:border-gray-800/60 bg-surfaceLight dark:bg-surfaceDark">
        <section id="developer" className="py-16 sm:py-20">
          <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
            <div className="flex flex-col md:flex-row items-center gap-8 bg-white dark:bg-cardDark p-8 rounded-3xl border border-gray-200 dark:border-gray-700/50 shadow-xl shadow-primary/5">
              
              {/* Left Side: Avatar */}
              <motion.div 
                {...fadeUp(0)}
                className="w-32 h-32 md:w-40 md:h-40 rounded-full overflow-hidden border-4 border-primary/20 dark:border-primaryDark/30 flex-shrink-0"
              >
                <img 
                  src="/images/hero_user.png" 
                  alt="Umang Pandey" 
                  className="w-full h-full object-cover object-top"
                />
              </motion.div>

              {/* Right Side: Text & Socials */}
              <div className="flex-1 text-center md:text-left">
                <motion.div {...fadeUp(0.05)} className="inline-flex items-center gap-2 mb-3 px-3 py-1 rounded-full bg-primary/10 dark:bg-primaryDark/15 text-xs text-primary dark:text-primaryDark font-bold uppercase tracking-wider">
                  The Creator
                </motion.div>
                <h2 className="text-2xl sm:text-3xl font-extrabold text-gray-900 dark:text-white mb-3">
                  Umang Pandey
                </h2>
                <p className="text-sm text-gray-500 dark:text-gray-400 mb-6 leading-relaxed max-w-xl">
                  Hi, I'm the developer behind MindMetric. I built this platform to make validated psychological research and self-awareness tools accessible to everyone for free. Let's connect!
                </p>
                
                {/* Social Buttons */}
                <motion.div {...fadeUp(0.1)} className="flex flex-wrap justify-center md:justify-start gap-4">
                  <a 
                    href="https://github.com/Umangpandey75"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="inline-flex items-center gap-2 px-5 py-2.5 rounded-xl border border-gray-200 dark:border-gray-700 hover:border-gray-300 dark:hover:border-gray-600 bg-gray-50 dark:bg-[#12122A] hover:bg-gray-100 dark:hover:bg-white/5 text-sm font-semibold text-gray-700 dark:text-gray-200 transition-all duration-200 hover:scale-105"
                  >
                    <GithubIcon className="w-4 h-4" />
                    GitHub
                  </a>
                  <a 
                    href="https://www.linkedin.com/in/umang-pandey-01b486273/"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="inline-flex items-center gap-2 px-5 py-2.5 rounded-xl border border-gray-200 dark:border-gray-700 hover:border-primary/30 dark:hover:border-primaryDark/30 bg-gray-50 dark:bg-[#12122A] hover:bg-primary/5 dark:hover:bg-primaryDark/5 text-sm font-semibold text-gray-700 dark:text-gray-200 hover:text-primary dark:hover:text-primaryDark transition-all duration-200 hover:scale-105"
                  >
                    <LinkedinIcon className="w-4 h-4" />
                    LinkedIn
                  </a>
                  <a 
                    href="https://umangpandey.vercel.app/"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="inline-flex items-center gap-2 px-5 py-2.5 rounded-xl border border-gray-200 dark:border-gray-700 hover:border-accent/30 bg-gray-50 dark:bg-[#12122A] hover:bg-accent/5 text-sm font-semibold text-gray-700 dark:text-gray-200 hover:text-accent transition-all duration-200 hover:scale-105"
                  >
                    <Globe size={16} />
                    Portfolio
                  </a>
                </motion.div>
              </div>

            </div>
          </div>
        </section>
      </div>

    </div>
  )
}
